spring:
  kafka:
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "com.github.pedrobacchini.*"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
amazon:
  dynamodb:
    endpoint: ${DYNAMO_ENDPOINT:http://localhost:4566}
  region: ${AWS_REGION:us-east-1}
  aws:
    dynamo:
      table: ${USER_TABLE:User}